### ISSUE TITLE
ProcessExitedException: process 0 (2x 4090)

### ISSUE THREAD

**Issue by Pugio** [AnswerDotAI/fsdp_qlora#24]
I'm trying what looks like the "Hello World" of this repo: Running the basic training on a Runpod community cloud `2 x RTX 4090, (128 vCPU 125 GB RAM)` configuration. Normally I'd play around with this for longer before posting an issue, but since Runpod was mentioned explicitly in the Answer.ai intro post, I figure this will be the simplest path for anybody trying to test this out.

On their `runpod/pytorch:2.2.0-py3.10-cuda12.1.1-devel-ubuntu22.04` pod:
```
python train.py \
--model_name meta-llama/Llama-2-70b-hf \
--batch_size 2 \
--context_length 2048 \
--precision bf16 \
--train_type qlora \
--use_gradient_checkpointing true \
--use_cpu_offload true \
--dataset alpaca \
--reentrant_checkpointing true \
--log_to wandb
```

Download the Llama-2 mode, sets everything up, and dies with the following backtrace:

```
Traceback (most recent call last):                                                                           
  File "/root/fsdp_qlora/train.py", line 939, in <module>                                                    
    def main(                                                                                                
  File "/usr/local/lib/python3.10/dist-packages/fastcore/script.py", line 125, in call_parse                 
    return _f()                                                                                              
  File "/usr/local/lib/python3.10/dist-packages/fastcore/script.py", line 119, in _f                         
    return tfunc(**merge(args, args_from_prog(func, xtra)))                                                  
  File "/root/fsdp_qlora/train.py", line 1010, in main                                                       
    mp.spawn(fsdp_main,                                                                                      
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 241, in spawn          
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")                             
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():                                                                                
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 140, in join           
    raise ProcessExitedException(                                                                            
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL  
```

Log:
```
1 Creating model 0
2 Loading model 0
3 Model created 0 1.119 GB
4 trainable params: 744,488,960 || all params: 35,495,616,512 || trainable%: 2.097410985236193
5 Wrapping model w/ FSDP 0
6 Wrapped model 0 1.444 GB
7 Applying activation checkpointing 0
8 Total Training Steps: 12940
9 Epoch 0, Loss 0.000:   0%|                                                                                                                             | 0/12940 [00:00<?, ?it/s]
```

Here's the [W&B run](https://wandb.ai/learn-ventures/fsdp_qlora/runs/4tgeyqno/overview).

I haven't found any indicators as to what's going on. Both System and GPU ram seem well within bounds, so I'm not sure why it's dying (unless maybe 125ּGB system ram is not enough, and getting blown through instantaneously before it's visible on `nvitop` or the W&B log?)

**Comment by zabirauf** [comment]
I suppose you are using SSH to login and run the training. The likely issue with that is that when your SSH session disconnects it will terminate processes that you started. The approach to have it running even when you disconnect is to use something like tmux.

I ran into similar issue and here is what I did

```
tmux new -s session_name
# run all the commands
```

When you ssh again and need to attach to same session you can do the following
```
#Confirm that your session is still alive
tmux ls

tmux attach -t session_name
```

when you want to detach from tmux session you can use Ctrl+b & d

P.S: Something like `nohup` with `& `at end of command doesn't work (in my experience) as torch has its own termination handler

**Comment by Pugio** [comment]
I appreciate the thoughtful response, but in this case I don't think that's what's happening. Firstly I'm remaining connected with a live session (remember this is crashing before it even gets to run one training step) . I'm also running this inside of a `screen` session, which has the same basic behavior as `tmux`.

Hopefully I'll have a chance to work more on debugging this today.

**Comment by sanipanwala** [comment]
@zabirauf 

I'm also facing the same issue.

`torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL  `

Also, I run my script using the screen command.

Thanks.

**Comment by Pugio** [comment]
I think it will be helpful to figure out how much System RAM is needed to do something like Llama 70B. The basic 2x4090 Runpod gives you `125 GB`. When I tried the same command on a 4x4090 with `251 GB RAM` the training started without a hitch. I don't think this is due to the extra 2 GPUs, because each GPU is only at about 40% memory usage.

I might try another test using the same `251 GB RAM` machine, but using only 2 of the GPUs to confirm this.

**Comment by SangJunni** [comment]
I am trying to run this project using 2x4090 and find out that the same issue occured.
My error message was `torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGKILL`

When I changed my RAM setting 64GB to 200 GB, repository train.py works fine.
I think it needs much more RAM memory described in README.md.
Maybe between 128GB to 200GB

**Comment by SangJunni** [comment]
@sanipanwala Can you allocate more than 200GB RAM then test to run train.py?
I am working this project with private server using SSH connection.

**Comment by sanipanwala** [comment]
@SangJunni I also used a private server and I think 190 GB is enough to run this program.

Thanks.

**Comment by johnowhitaker** [comment]
Running the example with a 70B model on 2 GPUs currently uses just over 128GB RAM, so systems with less than that will have issues. I've updated the readme to add a note on this and one potential fix: on my machine (128GB CPU RAM + 2x3090) I create a 10GB swapfile and this is enough to handle the RAM spike during loading before the training starts and it settles into a lower steady-state usage.

**Comment by Pugio** [comment]
That makes perfect sense, thank you. Maybe I'll put that into a gist for starting this up on Runpod.

**Comment by sanipanwala** [comment]
@johnowhitaker ,

I'm using the below command.

python train.py --model_name codellama/CodeLlama-70b-hf --batch_size 2 --context_length 512 --precision bf16 --train_type qlora --use_gradient_checkpointing true --use_cpu_offload true --dataset sql --reentrant_checkpointing true

Do you know why loss is always `nan`? I'm using `"knowrohit07/know_sql"` dataset. 

Thanks.

**Comment by johnowhitaker** [comment]
@sanipanwala how soon does the issue occur? I have that running now (I only had a llama-2-70b fine-tune not codellama handy) and so far the loss isn't nan. And perhaps you can share your environment so we can try to replicate?

**Comment by sanipanwala** [comment]
@johnowhitaker 

I have changed the precisions (bf16 to fp32 and other options) and learning rate but still have the same issue. 

If you have any suggestions then please let me know.

Thanks.

**Comment by johnowhitaker** [comment]
@sanipanwala can you try with llama 7B to see if it's codellama-specific or something else that's going wrong? I ran your command on the models I had handy and none gave nan losses. 
>I'm using my private computer, so it is not possible to share that environment.
Sorry, by 'share your environment' I meant tell us what versions of the libraries are installed so we can see if it might be related to that. SPecifically these libraries:
```
accelerate                
bitsandbytes            
datasets                  
hqq                       
hqq-aten              
huggingface-hub 
llama-recipes       
peft                      
safetensors         
tokenizers           
torch                    
transformers       
```
If you've already tried lowering the learning rate I'm not sure what else could be the issue.

**Comment by sanipanwala** [comment]
Hi @johnowhitaker ,

Please let me know if any other information you require.

Thanks.

**Comment by hsb1995** [comment]
Have you solved this problem? I have encountered the same problem and am still solving it.
I would like to consult with you on how to resolve the issue?
I have all the packages mentioned in his code @sanipanwala

**Comment by sanipanwala** [comment]
@hsb1995 ,

Not yet. I haven't found any solution to this issue. 

I have changed the precisions (bf16 to fp32 and other options) and learning rate but have the same issue.

Thanks,
Sani

**Comment by hsb1995** [comment]
Have you also tried the Qlora option command ?
---- Replied Message ----
| From | ***@***.***> |
| Date | 4/9/2024 09:58 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [AnswerDotAI/fsdp_qlora] ProcessExitedException: process 0 (2x 4090) (Issue #24) |

@hsb1995 ,

Not yet. I haven't found any solution to this issue.

I have changed the precisions (bf16 to fp32 and other options) and learning rate but have the same issue.

Thanks,
Sani

**Comment by hsb1995** [comment]
![image](https://github.com/AnswerDotAI/fsdp_qlora/assets/149936473/10a34d2a-5931-453f-a5ea-ca5a19a1be50)
I just tested that files with small weights can be computed in parallel, but files with large weights cannot. This indicates that it is not an issue with our hardware and software.

![image](https://github.com/AnswerDotAI/fsdp_qlora/assets/149936473/c75ec9ea-754f-44d9-b4ba-222787165a41)

**Comment by sanipanwala** [comment]
Hi @hsb1995 ,

Yes, 7B is working fine without an issue with the parallel process.

Have you also tried the Qlora option command?
=> Yes, I have tried but the same issue.

Thanks,
Sani

**Comment by hsb1995** [comment]
> Hi @hsb1995 ,
> 
> Yes, 7B is working fine without an issue with the parallel process.
> 
> Have you also tried the Qlora option command? => Yes, I have tried but the same issue.
> 
> Thanks, Sani

I am also solving this problem, and I have been complaining about it for two days without any clue.
On the webpage, it is said that the 70B model can be trained on two 3090/4090 blocks, but I feel that there are still many problems. The author mentioned in the reply message that it was an SSH connection issue. After reading all the issues, there are indeed many people who have encountered such problems but still haven't solved them. The author also did not clarify.

**Comment by hsb1995** [comment]
![image](https://github.com/AnswerDotAI/fsdp_qlora/assets/149936473/f3ff9f2e-5e17-4dd6-8742-46423ef06509)
![image](https://github.com/AnswerDotAI/fsdp_qlora/assets/149936473/115ddbda-0596-47e4-b5a8-05c068cf8fe6)
The command he mentioned in the article requires 128G-CPU, which is currently the case with me. Is it related to this? Or can you take a look at your CPU and see if it meets the requirements?

**Comment by hsb1995** [comment]
@sanipanwala

**Comment by sanipanwala** [comment]
Hi @hsb1995 ,

Yes, I have 128 GB CPU RAM and the swap memory is 116 GB.

Thanks,
Sani

**Comment by hsb1995** [comment]
Is this a bit awkward for me? Is it because of this reason that the operation did not succeed? 
@sanipanwala

**Comment by hsb1995** [comment]
I feel that my failure was caused by the CPU, and I tried other commands but still couldn't succeed.
@johnowhitaker But it's strange why you didn't succeed either. Because all your conditions are met.

**Comment by sanipanwala** [comment]
@hsb1995 ,

I'm not sure, but even the 70B model is producing NaN results during training. I think this could be due to a library version issue

Thanks,
Sani

**Comment by hsb1995** [comment]
![image](https://github.com/AnswerDotAI/fsdp_qlora/assets/149936473/226020b9-5da3-4b85-8bec-90189900eea7)
![image](https://github.com/AnswerDotAI/fsdp_qlora/assets/149936473/0bf27e09-5d20-4b5c-9d92-1d561138ac76)
Why does the pre training weight after running decrease by a lot of files? How can I use the trained files for downstream tasks? Do you know? I used a weight of 13B.
@sanipanwala

**Comment by sanipanwala** [comment]
Hi @hsb1995 ,

Why does the pre training weight after running decrease by a lot of files?
=> It might be due to the settings in your TrainingArguments.

`python train.py --model_name meta-llama/Llama-2-13b-hf --train_type qlora --dataset ds --batch_size 8 --lr_scheduler cosine --save_model True --output_dir ds_13B --gradient_accumulation_steps 2 --lr 2e-4.`

Using the above command you can use 13B.

Thanks

**Comment by hsb1995** [comment]
> Hi @hsb1995 ,
> 
> Why does the pre training weight after running decrease by a lot of files? => It might be due to the settings in your TrainingArguments.
> 
> `python train.py --model_name meta-llama/Llama-2-13b-hf --train_type qlora --dataset ds --batch_size 8 --lr_scheduler cosine --save_model True --output_dir ds_13B --gradient_accumulation_steps 2 --lr 2e-4.`
> 
> Using the above command you can use 13B.
> 
> Thanks

Hi, thank you for helping me with this matter.
Has dual parallel LLAMA-65B been resolved? I saw that the official updated the new code yesterday.

**Comment by hsb1995** [comment]
I received a ". safetensors" file, and the final file generated by the 13B model is 6GB.
In theory, shouldn't this pre trained weight generate many small files similar to the 13B weight?
But in the end, there was only one 6G file, which felt a bit strange.
![image](https://github.com/AnswerDotAI/fsdp_qlora/assets/149936473/7ea76c13-7d12-45b9-858c-552b55b8c805)

How can this ". safesensors" be used for downstream tasks?

**Comment by sanipanwala** [comment]
@hsb1995 

You can use the below code.

f```
rom transformers import AutoTokenizer
import transformers
import torch

model = "Your model path"

tokenizer = AutoTokenizer.from_pretrained(model)
pipeline = transformers.pipeline(
    "text-generation",
    model=model,
    torch_dtype=torch.float16,
    device_map="auto",
)

sequences = pipeline(
    'import socket\n\ndef ping_exponential_backoff(host: str):',
    do_sample=True,
    top_k=10,
    temperature=0.1,
    top_p=0.95,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
    max_length=200,
)
for seq in sequences:
    print(f"Result: {seq['generated_text']}")
```

Also Can you please share the command and parameter you have used?

Thanks,
Sani

**Comment by hsb1995** [comment]
> @hsb1995
> 
> You can use the below code.
> 
> ```
> 
> from transformers import AutoTokenizer
> import transformers
> import torch
> 
> model = "Your model path"
> 
> tokenizer = AutoTokenizer.from_pretrained(model)
> pipeline = transformers.pipeline(
>     "text-generation",
>     model=model,
>     torch_dtype=torch.float16,
>     device_map="auto",
> )
> 
> sequences = pipeline(
>     'import socket\n\ndef ping_exponential_backoff(host: str):',
>     do_sample=True,
>     top_k=10,
>     temperature=0.1,
>     top_p=0.95,
>     num_return_sequences=1,
>     eos_token_id=tokenizer.eos_token_id,
>     max_length=200,
> )
> for seq in sequences:
>     print(f"Result: {seq['generated_text']}")
> ```
> 
> Also Can you please share the command and parameter you have used?
> 
> Thanks, Sani

--world_size
2
--master_port
12356
--model_name
${}$
--gradient_accumulation_steps
4
--batch_size
1
--context_length
512
--save_model
True
--output_dir
${}$
--precision
bf16
--train_type
qlora
--reentrant_checkpointing
true
--use_gradient_checkpointing
true
--use_cpu_offload
false
--use_activation_cpu_offload
false
--log_to
wandb
--dataset
alpaca

**Comment by hsb1995** [comment]
> @hsb1995
> 
> You can use the below code.
> 
> ```
> 
> from transformers import AutoTokenizer
> import transformers
> import torch
> 
> model = "Your model path"
> 
> tokenizer = AutoTokenizer.from_pretrained(model)
> pipeline = transformers.pipeline(
>     "text-generation",
>     model=model,
>     torch_dtype=torch.float16,
>     device_map="auto",
> )
> 
> sequences = pipeline(
>     'import socket\n\ndef ping_exponential_backoff(host: str):',
>     do_sample=True,
>     top_k=10,
>     temperature=0.1,
>     top_p=0.95,
>     num_return_sequences=1,
>     eos_token_id=tokenizer.eos_token_id,
>     max_length=200,
> )
> for seq in sequences:
>     print(f"Result: {seq['generated_text']}")
> ```
> 
> Also Can you please share the command and parameter you have used?
> 
> Thanks, Sani

But this is just the weight of llama2-13B

**Comment by sanipanwala** [comment]
@hsb1995 

Once a model is saved on our side, it will store the adapter.config file and safesensors and other files also. Please check all the files are stored properly on your side.

Then using the above code it will give you an answer based on your training.

Thanks.

**Comment by hsb1995** [comment]
Dear Professor, @sanipanwala 
<img width="1040" alt="Image" src="https://github.com/AnswerDotAI/fsdp_qlora/assets/149936473/93aa3e6a-fa44-44d2-a36c-5a44fbde985b">
I followed the command you gave me:
![image](https://github.com/AnswerDotAI/fsdp_qlora/assets/149936473/391b0f8f-6dd6-4243-bc16-0b3c5a6183c1)
I completed the training, but I checked all my folders and only the following files were trained in the end:
![image](https://github.com/AnswerDotAI/fsdp_qlora/assets/149936473/8ef5124e-3c48-4134-bba3-4d6d2ccb4799)

Finally, I took these files and followed the code you provided me to perform downstream tasks. I feel that there is still a problem with missing files. Then I was afraid that I was not training properly, so I went to train again. I finally confirmed that there is no problem on my end. All the files are here, but there are still some missing files. The errors in doing downstream tasks are as follows:
![image](https://github.com/AnswerDotAI/fsdp_qlora/assets/149936473/e689c713-0a97-4ba0-9a95-f1f53a0487b7)
I checked all the files and only generated the config.yaml file. There is no config.json. So how should we do downstream tasks like this?

**Comment by sanipanwala** [comment]
@hsb1995 

You can try the below a Code. Please make modifications as per your requirements.
```

import torch
from safetensors.torch import load_safetensors
from transformers import AutoModelForCausalLM, AutoTokenizer

# Path to your .safetensors file
file_path = "model_state_dict.safetensors"

# Load the model state dictionary from .safetensors file
state_dict = load_safetensors(file_path)

# Initialize the model architecture to match the state dictionary
model = AutoModelForCausalLM.from_pretrained('modelname')  # use a placeholder to set up structure
model.load_state_dict(state_dict)  # load the actual state dict

# Set the model to evaluation mode if you are doing inference
model.eval()

# Initialize the tokenizer
tokenizer = AutoTokenizer.from_pretrained('modelname')

# Sample input text
input_text = "Hello, how are you doing today?"

# Encode the text using the same tokenizer used during training
encoded_input = tokenizer(input_text, return_tensors='pt')

# Perform inference (no gradient calculations needed)
with torch.no_grad():
    outputs = model(**encoded_input)

# Retrieve the logits (or any other outputs you are interested in)
logits = outputs.last_hidden_state

# Print out the logits
print(logits)

# Assuming you want to do something with the logits, here's a placeholder for that logic
# You can replace this with your actual downstream task
print("Inference completed. Output tensor shape:", logits.shape

```

Thanks,
Sani
