### ISSUE TITLE
Issues with LLaMA-3-70B

### ISSUE THREAD

**Issue by catid** [AnswerDotAI/fsdp_qlora#54]
Testing with this script on 4x H100s with 80GB VRAM and 2T system RAM:

```
python train.py \
  --model_name meta-llama/Meta-Llama-3-70B-Instruct \
  --batch_size 32 \
  --context_length 8192 \
  --precision bf16 \
  --train_type hqq_dora \
  --use_gradient_checkpointing true \
  --use_cpu_offload true \
  --dataset alpaca \
  --verbose true
```

I get this result after `Wrapping model w/ FSDP 0`:

```
- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/fq/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/root/fsdp_qlora/train.py", line 724, in fsdp_main
    model = FSDP(
  File "/root/miniconda3/envs/fq/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 477, in __init__
    _auto_wrap(
  File "/root/miniconda3/envs/fq/lib/python3.10/site-packages/torch/distributed/fsdp/_wrap_utils.py", line 101, in _auto_wrap
    _recursive_wrap(**recursive_wrap_kwargs, **root_kwargs)  # type: ignore[arg-type]
  File "/root/miniconda3/envs/fq/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 543, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  File "/root/miniconda3/envs/fq/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 543, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  File "/root/miniconda3/envs/fq/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 543, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  [Previous line repeated 1 more time]
  File "/root/miniconda3/envs/fq/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 561, in _recursive_wrap
    return _wrap(module, wrapper_cls, **kwargs), nonwrapped_numel
  File "/root/miniconda3/envs/fq/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 490, in _wrap
    return wrapper_cls(module, **kwargs)
  File "/root/miniconda3/envs/fq/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 503, in __init__
    _init_param_handle_from_module(
  File "/root/miniconda3/envs/fq/lib/python3.10/site-packages/torch/distributed/fsdp/_init_utils.py", line 548, in _init_param_handle_from_module
    _materialize_with_param_init_fn(
  File "/root/miniconda3/envs/fq/lib/python3.10/site-packages/torch/distributed/fsdp/_init_utils.py", line 851, in _materialize_with_param_init_fn
    param_init_fn(module)
  File "/root/fsdp_qlora/train.py", line 734, in <lambda>
    param_init_fn=lambda module: module.to_empty(device=torch.device("cuda"), recurse=False)
  File "/root/hqq/hqq/core/quantize.py", line 480, in to_empty
    return self.cuda(device)
  File "/root/hqq/hqq/core/quantize.py", line 414, in cuda
    self.W_q.data, self.meta = Quantizer.cuda(self.W_q.data, self.meta, device)
  File "/root/hqq/hqq/core/quantize.py", line 215, in cuda
    return Quantizer.to_inplace(W_q, meta, device=device)
  File "/root/hqq/hqq/core/quantize.py", line 176, in to_inplace
    W_q = W_q.to(device).contiguous()
NotImplementedError: Cannot copy out of meta tensor; no data!

/root/miniconda3/envs/fq/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Seems to be running out of VRAM at this point and moving something to CPU and failing I guess?

**Comment by catid** [comment]
Ah nevermind I see the README: `Pin commit to 72b2b641aadc44a7ded6b243915f90df3b3be385 for FSDP compatibility, until to_empty() method is fixed.`
